name: eie_vision_new
channels:
  - nvidia
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  # - pytorch=2.2  # Or latest stable version
  - pytorch             # latest stable version (i.e. installed 2.5.1 in 05/2025)
  - torchvision
  - pytorch-cuda=12.1   # Compatible with Ioannis' NVIDIA driver (535)
  - scipy
  - ipykernel
  - jupytext
  - pip:
      - dominate
      - lpips
      - tensorboardX
      - tensorboard
      - crc32c
